# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.22
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 15.0
org_name: Camptocamp
org_slug: Camptocamp
rebel_module_groups: []
repo_description: Tools modules for odoo projects
repo_name: Tools modules for odoo projects
repo_slug: odoo-tools
repo_website: https://www.camptocamp.com
use_pyproject_toml: false
use_ruff: true
