# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.27
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: true
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 18.0
org_name: Camptocamp
org_slug: camptocamp
rebel_module_groups: []
repo_description: Tools modules for odoo projects
repo_name: Tools modules for odoo projects
repo_slug: odoo-tools
repo_website: https://github.com/camptocamp/odoo-tools
use_pyproject_toml: true
use_ruff: true

